using Bogus;
using HospitalAPI.Models;

namespace HospitalAPI.Fakers
{
    public class DoctorFaker : Faker<Doctor>
    {
        private IEnumerable<string> qualifications = new string[] { "MD",
    "DO",
    "MBBS",
    "MBChB",
    "BMed",
    "BDS",
    "DMD",
    "DDS",
    "MS",
    "MCh",
    "DSc",
    "PhD",
    "FRCP",
    "FRCS",
    "FACS",
    "FACP",
    "FAAP",
    "FCPS",
    "FRCOG",
    "MRCP",
    "MRCS",
    "MRCGP",
    "MRCOG",
    "DABEM",
    "DABFM",
    "DABP",
    "DABPN",
    "DABR",
    "DABPM",
    "DABCC",
    "DABMG",
    "FAAD",
    "FACP",
    "FACC",
    "FRCPath",
    "FASN",
    "FCVS",
    "FASCO",
    "FASMBS",
    "FACP",
    "FRCOG",
    "FRCA",
    "FANZCA",
    "FRCSI",
    "FFARCSI",
    "FFRCSI",
    "FRCGP",
    "FRCSEd",
    "FRCOphth",
    "FRCPath",
    "FCPD",
    "FRCS",
    "MRCGP",
    "MRCS",
    "MRCPath",
    "MRCP",
    "MRCOG",
    "MRCPCH",
    "MRCPsych",
    "MRCSLT",
    "MRCVS",
    "MRad",
    "MRadA",
    "FRANZCP",
    "FRACP",
    "FRACS",
    "FRCOG",
    "FRCPA"};
        List<string> doctorSpecializations = new List<string>()
{
    "Cardiology",
    "Dermatology",
    "Endocrinology",
    "Gastroenterology",
    "Hematology",
    "Infectious Diseases",
    "Nephrology",
    "Neurology",
    "Oncology",
    "Pulmonology",
    "Rheumatology",
    "Allergy & Immunology",
    "Anesthesiology",
    "Emergency Medicine",
    "Family Medicine",
    "Internal Medicine",
    "Obstetrics & Gynecology",
    "Ophthalmology",
    "Orthopedics",
    "Otolaryngology",
    "Pathology",
    "Pediatrics",
    "Psychiatry",
    "Radiology",
    "Surgery",
    "Urology",
    "Neurosurgery",
    "Cardiac Surgery",
    "Plastic Surgery",
    "Thoracic Surgery",
    "Vascular Surgery",
    "Pediatric Surgery",
    "Geriatrics",
    "Physical Medicine & Rehabilitation",
    "Sports Medicine",
    "Nuclear Medicine",
    "Pain Medicine",
    "Sleep Medicine",
    "Interventional Radiology",
    "Gynecologic Oncology",
    "Maternal-Fetal Medicine",
    "Reproductive Endocrinology & Infertility",
    "Critical Care Medicine",
    "Hospital Medicine",
    "Infectious Disease",
    "Clinical Pharmacology",
    "Medical Genetics",
    "Hyperbaric Medicine",
    "Undersea Medicine",
    "Tropical Medicine",
    "Phlebology",
    "Addiction Medicine",
    "Bariatric Medicine",
    "Geriatric Medicine",
    "Integrative Medicine",
    "Occupational Medicine",
    "Public Health & General Preventive Medicine",
    "Aerospace Medicine",
    "Clinical Informatics",
    "Medical Toxicology",
    "Sleep Medicine",
    "Sports Medicine",
    "Travel Medicine",
    "Adolescent Medicine",
    "Hospice & Palliative Medicine",
    "Pain Medicine",
    "Sexual Medicine",
    "Telemedicine",
    "Urgent Care Medicine"
};
        public Guid Guid_ {  get;  set; }
        public DoctorFaker() 
        {
            RuleFor(d => d.Id, Guid.NewGuid());
            RuleFor(d => d.Qualifications, f => qualifications.ElementAt(f.Random.Number(0, qualifications.Count() - 1)));
            RuleFor(d => d.Specialization, f => doctorSpecializations.ElementAt(f.Random.Number(0, doctorSpecializations.Count)));
            RuleFor(d => d.StaffId, f => Guid_);
        }
    }
}
